Repository obscuritylabs/dramatiq-mongodb, pull requests merged in 2022-01, with the labels that each got.

#21 docs: Format Obscurity Labs LLC Vulnerability Disclosure Policy
  .github/SECURITY.md
Labels: documentation, good first issue

#31 docs: Add Bug Report and Feature Request Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#32 Issue 8 create cd pipeline to publish to GitHub releases
  .github/workflows/cd.yaml
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
Labels: merge when passing

#40 Hotfix/cd pipeline
  pyproject.toml
Labels: merge when passing
